enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
patches-version = "dev"

[YouTube]
enabled = true
app-name = "YouTube"
build-mode = "both"#both means packing both apk and module at the same time. To pack only mask module, change both to module
version = "19.16.39"#Remember to check the patch support version before each package
rv-brand = "ReVanced Extended"
#Remember to change these two versions when the patch is updated
#uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
excluded-patches = "'Custom branding name for YouTube'"#Exclusion list
included-patches = "'MaterialYou''Return YouTube Username''Custom header for YouTube'"#Mandatory inclusion list Patches have a default list, some are disabled by default
arch = "arm64-v8a"
patcher-args = "-e'Custom branding icon for YouTube' -OappIcon='squid_game' -e 'Visual preferences icons for YouTube' -OsettingsMenuIcon='revanced_colored' -e 'Custom header for YouTube' -OcustomHeader='custom_branding_icon' -e 'Theme' -OdarkThemeBackgroundColor=#FF111111"

[Instagram]
enabled = true
build-mode = "both"
patches-source = "Aunali321/ReVancedExperiments"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram/"
version = "357.1.0.52.100"
arch = "arm64-v8a"  

[Telegram]
enabled = true
build-mode = "both"
patches-source = "Aunali321/ReVancedExperiments"
uptodown-dlurl = "https://telegram.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/telegram-fz-llc/telegram/"
version = "auto"
